name: testflow

on:
  push:
    branches:
      - feat/ci/cd

env:
  POSTGRES_USER: test
  POSTGRES_PASSWORD: test
  POSTGRES_DB: test

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t your-docker-image-name .

      - name: Run Docker Containers
        run: |
          echo --- Running test cases ---
          docker run --rm your-docker-image-name
          echo --- Completed test cases ---

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build
        run: docker build -t your-docker-image-name .

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Publish
        run: docker push your-docker-image-name
