name: CI/CD Workflow

on:
  push:
    branches:
      - feat/ci/cd  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Run Lighthouse Tests
        run: npx lighthouse http://localhost:3000
